<a href="https://colab.research.google.com/github/horiaahmed/DelayedFlight-Analysis/blob/main/DelayedFlightsEDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/DelayedFlights.csv')

In [ ]:
df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0.0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(444469, 30)

In [ ]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [ ]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,N,0.0,2.0,0.0,0.0,0.0,32.0
4,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,4.0,10.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444469 entries, 0 to 444468
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Year               444469 non-null  int64
 1   Month              444469 non-null  int64
 2   DayofMonth         444469 non-null  int64
 3   DayOfWeek          444469 non-null  int64
 4   DepTime            444469 non-null  float64
 5   CRSDepTime         444469 non-null  int64
 6   ArrTime            442681 non-null  float64
 7   CRSArrTime         444469 non-null  int64
 8   UniqueCarrier      444469 non-null  object
 9   FlightNum          444469 non-null  int64
 10  TailNum            444468 non-null  object
 11  ActualElapsedTime  442681 non-null  float64
 12  CRSElapsedTime     444391 non-null  float64
 13  AirTime            442681 non-null  float64
 14  ArrDelay           442681 non-null  float64
 15  DepDelay           444469 non-null  float64
 16  Origin             444469 non-null  object
 17  Dest               444469 non-null  object
 18  Distance           444469 non-null  int64
 19  TaxiIn             442681 non-null  float64
 20  TaxiOut            444469 non-null  float64
 21  Cancelled          444469 non-null  int64
 22  CancellationCode   444468 non-null  object
 23  Diverted           444468 non-null  float64
 24  CarrierDelay       294320 non-null  float64
 25  WeatherDelay       294320 non-null  float64
 26  NASDelay           294320 non-null  float64
 27  SecurityDelay      294320 non-null  float64
 28  LateAircraftDelay  294320 non-null  float64
dtypes: float64(15), int64(9), object(5)
memory usage: 98.3+ MB

In [ ]:
df.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,444469.0,444469.000000,444469.000000,444469.000000,444469.000000,444469.000000,442681.000000,444469.000000,444469.000000,442681.000000,...,444469.000000,442681.000000,444469.000000,444469.0,444468.000000,294320.000000,294320.000000,294320.000000,294320.000000,294320.000000
mean,2008.0,1.747746,15.336174,3.925410,1512.506787,1457.552176,1610.044086,1622.469090,2340.811978,128.268030,...,720.690590,6.639113,17.764056,0.0,0.004023,18.775758,3.828370,13.788998,0.108161,26.129254
std,0.0,0.714102,8.844459,1.951607,446.611444,424.553979,536.067868,461.115508,1994.657616,68.138629,...,537.613055,5.054693,13.279672,0.0,0.063298,42.152365,22.165814,32.845595,1.958910,41.751168
min,2008.0,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,15.000000,...,24.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2008.0,1.000000,7.000000,2.000000,1157.000000,1125.000000,1315.000000,1315.000000,658.000000,78.000000,...,330.000000,4.000000,10.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2008.0,2.000000,16.000000,4.000000,1539.000000,1500.000000,1708.000000,1655.000000,1665.000000,112.000000,...,587.000000,5.000000,14.000000,0.0,0.000000,2.000000,0.000000,0.000000,0.000000,10.000000
75%,2008.0,2.000000,23.000000,5.000000,1857.000000,1813.000000,2026.000000,2007.000000,3756.000000,159.000000,...,954.000000,8.000000,21.000000,0.0,0.000000,21.000000,0.000000,13.000000,0.000000,35.000000
max,2008.0,3.000000,31.000000,7.000000,2400.000000,2359.000000,2400.000000,2400.000000,9740.000000,698.000000,...,4962.000000,189.000000,383.000000,0.0,1.000000,1455.000000,1148.000000,1357.000000,149.000000,1143.000000

In [ ]:
df.isnull().sum()

Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                1788
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   1
ActualElapsedTime      1788
CRSElapsedTime           78
AirTime                1788
ArrDelay               1788
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 1788
TaxiOut                   0
Cancelled                 0
CancellationCode          1
Diverted                  1
CarrierDelay         150149
WeatherDelay         150149
NASDelay             150149
SecurityDelay        150149
LateAircraftDelay    150149
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df = df[(df["Cancelled"] == 0) & (df["Diverted"] == 0)]
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,N,0.0,2.0,0.0,0.0,0.0,32.0
4,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,4.0,10.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444463,2008,3,25,2,1941.0,1929,2030.0,2025,OO,3793,...,4.0,11.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
444464,2008,3,25,2,2137.0,1905,2304.0,2016,OO,3809,...,4.0,35.0,0,N,0.0,168.0,0.0,0.0,0.0,0.0
444465,2008,3,25,2,723.0,700,848.0,830,OO,3851,...,5.0,19.0,0,N,0.0,18.0,0.0,0.0,0.0,0.0
444466,2008,3,25,2,1710.0,1655,1835.0,1825,OO,3866,...,6.0,25.0,0,N,0.0,NaN,NaN,NaN,NaN,NaN
444467,2008,3,25,2,1023.0,1005,1210.0,1144,OO,3887,...,4.0,33.0,0,N,0.0,26.0,0.0,0.0,0.0,0.0

In [ ]:
delay_cols = [
    "CarrierDelay","WeatherDelay",
    "NASDelay","SecurityDelay",
    "LateAircraftDelay"
]

df[delay_cols] = df[delay_cols].fillna(0)

In [ ]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0
3,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,N,0.0,2.0,0.0,0.0,0.0,32.0
4,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,4.0,10.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.isnull().sum()

Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [ ]:
df['OnTime']=(df['ArrDelay']<=15).astype(int)

In [ ]:
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,OnTime
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,8.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,10.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,17.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1
3,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,10.0,0,N,0.0,2.0,0.0,0.0,0.0,32.0,0
4,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,10.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444463,2008,3,25,2,1941.0,1929,2030.0,2025,OO,3793,...,11.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1
444464,2008,3,25,2,2137.0,1905,2304.0,2016,OO,3809,...,35.0,0,N,0.0,168.0,0.0,0.0,0.0,0.0,0
444465,2008,3,25,2,723.0,700,848.0,830,OO,3851,...,19.0,0,N,0.0,18.0,0.0,0.0,0.0,0.0,0
444466,2008,3,25,2,1710.0,1655,1835.0,1825,OO,3866,...,25.0,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1
444467,2008,3,25,2,1023.0,1005,1210.0,1144,OO,3887,...,33.0,0,N,0.0,26.0,0.0,0.0,0.0,0.0,0

In [ ]:
df["DelayCategory"] = pd.cut(
    df["ArrDelay"],
    bins=[-1000,0,15,60,10000],
    labels=["Early","OnTime","Minor","Major"]
)

In [ ]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,OnTime,DelayCategory
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1,Early
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1,OnTime
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1,OnTime
3,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,0,N,0.0,2.0,0.0,0.0,0.0,32.0,0,Minor
4,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,...,0,N,0.0,0.0,0.0,0.0,0.0,0.0,1,OnTime

In [ ]:
df["Cancelled"].value_counts()
df["Diverted"].value_counts()

Diverted
0.0    442680
Name: count, dtype: int64

In [ ]:
df.to_csv('Cleaned_DelayFlight.csv',index=False)

In [ ]:
dff=pd.read_csv('/content/DelayedFlights.csv')

In [ ]:
dff["Cancelled"].value_counts()

Cancelled
0.0    452639
Name: count, dtype: int64

In [ ]:
dff["Diverted"].value_counts()

Diverted
0.0    450838
1.0      1801
Name: count, dtype: int64